version: '3.7'

services:
    v2_service:
        build:
            context: ./
            dockerfile: service_v2.dockerfile
        container_name: "v2_service"
        environment:
            - PORT=3001
            - API_KEY=${API_KEY_WEATHER_FORECAST}
        ports:
            - 3001:3001