version: '3.7'

services:
    mongodb_container:
        build:
            context: ./
            dockerfile: mongodb.dockerfile
        container_name: "mongodb_container" 
        ports:
            - 27017:27017
    
    mongodb_seed_container:
        build:
            context: ./
            dockerfile: mongodb_seed.dockerfile
        container_name: "mongodb_seed_container"
        ports:
            - 13000:3000
        links:
            - mongodb_container
        depends_on:
            - mongodb_container
